server {
  # Ascolta sulla porta 80 (che abbiamo esposto nel Dockerfile)
  listen 80;

  location / {
    # Indica la cartella dove si trovano i file statici
    root   /usr/share/nginx/html;
    index  index.html index.htm;

    # QUESTA È LA RIGA MAGICA:
    # Se il browser chiede un URL (es. /translate), Nginx non lo trova.
    # Questa riga gli dice: "Se non trovi il file, servi /index.html"
    # e lascia che React gestisca il routing.
    try_files $uri $uri/ /index.html;
  }

  # Configurazione opzionale per pagine di errore
  error_page   500 502 503 504  /50x.html;
  location = /50x.html {
    root   /usr/share/nginx/html;
  }
}