version: '3.8'

services:

  signspeak-ml:
    build:
      context: ./SignSpeak-ML
      dockerfile: Dockerfile
    container_name: signspeak-ml
    env_file:
      - ./SignSpeak-ML/.env
    ports:
      - "8000:8000"
    environment:
      - PYTHONUNBUFFERED=1
    volumes:
      - ./SignSpeak-ML/app:/app/app
      - ./SignSpeak-ML/app_models:/app/app_models

  signspeak-backend:
    build:
      context: ./SignSpeakBackend
      dockerfile: Dockerfile
    container_name: signspeak-backend
    ports:
      - "8080:8080"

#  signspeak-frontend:
#    build:
#      context: ./signspeak-frontend
#      dockerfile: Dockerfile
#    container_name: signspeak-frontend
#    ports:
#      - "5173:80"
#    depends_on:
#      - signspeak-backend

  signspeak-frontend:
    build:
      context: ./signspeak-frontend
      dockerfile: Dockerfile.dev
    container_name: signspeak-frontend
    ports:
      - "5173:5173"
    volumes:
      - ./signspeak-frontend:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
    depends_on:
      - signspeak-backend
