version: '3.8'

services:

  signspeak-backend:
    build:
      context: ./SignSpeakBackend
      dockerfile: Dockerfile
    container_name: signspeak-backend
    ports:
      - "8080:8080"

  signspeak-frontend:
    build:
      context: ./signspeak-frontend
      dockerfile: Dockerfile
    container_name: signspeak-frontend
    ports:
      - "5173:80"
    depends_on:
      - signspeak-backend