from collections import Counter

import torch
import numpy as np
from typing import Optional, Dict, Any, Type

from .models.GRUClassifier import GRUClassifier
from ..utils.config import settings


class ASLClassifier:
    """
    Production-ready wrapper for any ASL recognition model.
    Works as a stable interface between Pipeline and the underlying ML model.

    Responsibilities:
      - Load model from file
      - Keep class mappings
      - Prepare input tensors
      - Run inference (predict index / label / probabilities)
      - Allow easy model swapping (GRU, Transformer, CNN, etc.)
    """

    def __init__(
        self,
        model_path: str = settings.MODEL_PATH,
        device: str = settings.DEVICE,
        model_class: Optional[Type[torch.nn.Module]] = None,
        expected_frames: int = settings.EXPECTED_FRAMES,
    ):
        """
        Args:
            model_path: path to saved model .pt
            device: "cpu" or "cuda"
            model_class: override model type (default = GRUClassifier)
            expected_frames: fixed length for resampling inputs
        """
        self.device = device
        self.expected_frames = expected_frames

        # --- Support future model types ---
        self.model_class = model_class or GRUClassifier

        # --- Load model ---
        self.model = self.model_class.from_file(model_path, device=device)
        self.model.eval()

        # --- Metadata ---
        self.class_names = self.model.class_names
        self.class_to_idx = self.model.class_to_idx
        self.idx_to_class = {v: k for k, v in self.class_to_idx.items()}

    # ------------------------------------------------------------------
    # Internal helper — Convert (T,F) np.ndarray → torch tensor (1,T,F)
    # ------------------------------------------------------------------

    def _prepare_tensor(self, seq_np: np.ndarray) -> torch.Tensor:
        """
        Converts np.ndarray(T,F) to tensor(1,T,F) and moves to device.
        Assumes seq_np is already normalized and has correct shape.
        """
        if not isinstance(seq_np, np.ndarray):
            seq_np = np.array(seq_np, dtype=np.float32)

        x = torch.tensor(seq_np, dtype=torch.float32).unsqueeze(0)
        return x.to(self.device)

    # ------------------------------------------------------------------
    # Public API
    # ------------------------------------------------------------------

    def predict_index(self, seq_np: np.ndarray) -> int:
        """
        Returns the class index (int).
        """
        x = self._prepare_tensor(seq_np)
        with torch.no_grad():
            logits = self.model(x)
            idx = torch.argmax(logits, dim=1).item()
        return idx

    def predict_label(self, seq_np: np.ndarray) -> str:
        """
        Returns the predicted class label (str).
        """
        idx = self.predict_index(seq_np)
        return self.idx_to_class[idx]

    def predict_proba(self, seq_np: np.ndarray) -> Dict[str, float]:
        """
        Returns {label: probability}.
        """
        x = self._prepare_tensor(seq_np)
        with torch.no_grad():
            logits = self.model(x)
            probs = torch.softmax(logits, dim=1)[0]

        return {
            self.idx_to_class[i]: float(p)
            for i, p in enumerate(probs)
        }



    # ------------------------------------------------------------------
    # Convenience method for pipeline
    # ------------------------------------------------------------------

    def predict(self, seq_np: np.ndarray) -> str:
        """
        Standard prediction for Pipeline:
        returns a class label (str).
        """
        return self.predict_label(seq_np)

    def predict_tta(self, tta_segments: list[np.ndarray]) -> str:
        """
        TTA inference:
        - tta_segments: list of (60,F) numpy arrays generated by DataPreparer
        - returns: final predicted label (str) after majority vote
        """
        if not tta_segments:
            raise ValueError("predict_tta received empty segment list")

        preds = []

        for seq_np in tta_segments:
            # Standard single-sequence prediction
            label = self.predict(seq_np)  # already returns a str
            preds.append(label)

        # Majority vote (mode)
        counter = Counter(preds)
        final_label = counter.most_common(1)[0][0]

        return final_label

    # --- optional: return all predictions for debugging ---
    def predict_tta_debug(self, tta_segments: list[np.ndarray]):
        """
        Returns:
            {
                'votes': {'HELLO': 5, 'PHONE': 2},
                'final': 'HELLO',
                'raw_preds': ['HELLO','HELLO','PHONE',...]
            }
        """
        if not tta_segments:
            return {
                "votes": {},
                "final": None,
                "raw_preds": []
            }

        preds = [self.predict(seq) for seq in tta_segments]
        counter = Counter(preds)
        final = counter.most_common(1)[0][0]

        return {
            "votes": dict(counter),
            "final": final,
            "raw_preds": preds
        }
